version: '3.9'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on: 
      - client
      - server